// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

[#jdbc-integration]
== Bootique Integration with JDBC

JDBC is a standard and well-known API to access relational databases. To connect to a database you need a
connection pool (`javax.sql.DataSource`). https://github.com/bootique/bootique-jdbc[`bootique-jdbc`]
helps to configure one or more DataSources in your app. It also provides advanced APIs for
connection pool monitoring and database testing. `bootique-jdbc` is used by applications directly, as well as by
other Bootique modules that require database access (Cayenne, JOOQ, MyBatis, etc.).

Out of the box Bootique supports a choice of two connection pool providers:

* https://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html[Tomcat JDBC]
* https://github.com/brettwooldridge/HikariCP[HikariCP].

Both are production-quality. From the application perspective the difference is in configuration and available
<<jdbc-merics-and-healthchecks,metrics and health checks>>. Beyond that Bootique (and JDBC) gives you the API
abstraction common to both, so you can pick either one.

Import one of these Bootique modules in your app, depending on your connection pool choice:
[source,xml]
----
<!-- For Tomcat DataSource -->
<dependency>
    <groupId>io.bootique.jdbc</groupId>
    <artifactId>bootique-jdbc-tomcat</artifactId>
</dependency>
----

[source,xml]
----
<!-- For HikariCP -->
<dependency>
    <groupId>io.bootique.jdbc</groupId>
    <artifactId>bootique-jdbc-hikaricp</artifactId>
</dependency>
----

Alternatively you may include an <<jdbc-merics-and-healthchecks,"instrumented" version>> of each module, that will
enable a number of metrics for your running app.

You will also need to add JDBC driver jar to the app dependencies corresponding to your database.
