// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

[#jdbc-merics-and-healthchecks]
== Metrics and Health Checks

You may use the "instrumented" version of one of the `bootique-jdbc-*` connection pools, that will expose a number of
metrics and health checks:

.Maven
[%collapsible%open]
====
[source,xml]
----
<!-- For Tomcat DataSource -->
<dependency>
    <groupId>io.bootique.jdbc</groupId>
    <artifactId>bootique-jdbc-tomcat-instrumented</artifactId>
</dependency>
----

[source,xml]
----
<!-- For HikariCP -->
<dependency>
    <groupId>io.bootique.jdbc</groupId>
    <artifactId>bootique-jdbc-hikaricp-instrumented</artifactId>
</dependency>
----
====

.Gradle
[%collapsible]
====
[source,groovy]
----
// For Tomcat DataSource
{
  implementation: 'io.bootique.jdbc:bootique-jdbc-tomcat-instrumented'
}
----

[source,groovy]
----
// For HikariCP
{
  implementation: 'io.bootique.jdbc:bootique-jdbc-hikaricp-instrumented'
}
----
====