// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
=== HikariCP

HikariCP DataSource is produced by `io.bootique.jdbc.hikaricp.HikariCPManagedDataSourceFactory` and supports the
properties listed below (mostly matching
https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby[HikariCP docs]. In fact most of the descriptions
are adopted from that document). A typical config might look like this:

[source,yaml]
----
include::../../../test/resources/io/bootique/jdbc/docs/hikari-config.yml[tags=config]
----

.HikariCP DataSource Property Reference - Essential Properties
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`type`
|
|Indicates that the DataSource is produced by HikariCP. Can be either `hikari` or `hikari-instrumented`. Can be omitted
if `bootique-jdbc-hikaricp` is the only DataSourceFactory implementation in the app dependencies.

|`autoCommit`
|`true`
| Controls the default auto-commit behavior of connections returned from the pool.

|`connectionTestQuery`
|
| The query that will be executed just before a connection is given to the app from the pool to validate that the
connection to the database is still alive. This is for "legacy" drivers that do not support the JDBC4
`Connection.isValid()` API.

|`connectionTimeout`
| 30000
| Long value representing milliseconds. Controls the maximum number of milliseconds that the app will wait for a
connection from the pool. If this time is exceeded without a connection becoming available, a SQLException will be
thrown. Lowest acceptable connection timeout is 250 ms.

|`idleTimeout`
| 600000
| Long value representing milliseconds. Controls the maximum amount of time that a connection is allowed to sit idle in
the pool. This setting only applies when `minimumIdle` is defined to be less than `maximumPoolSize`. Idle connections
will not be retired once the pool reaches `minimumIdle` connections. Whether a connection is retired as idle or not is
subject to a maximum variation of +30 seconds, and average variation of +15 seconds. A connection will never be retired
as idle before this timeout. A value of 0 means that idle connections are never removed from the pool. The minimum
allowed value is 10000ms (10 seconds).

|`jdbcUrl`
|
| Database URL. Required for "DriverManager-based" configuration. (The alternative is "DataSource-based" config).

|`maximumPoolSize`
| 10
| Controls the maximum size that the pool is allowed to reach, including both idle and in-use connections. This value
will determine the maximum number of actual connections to the database backend. When the pool reaches this size, and
no idle connections are available, calls to `getConnection()` will block for up to `connectionTimeout` milliseconds
before timing out.

|`minimumIdle`
| same as `maximumPoolSize`
| Controls the minimum number of idle connections that HikariCP tries to maintain in the pool. If the idle connections
dip below this value and total connections in the pool are less than `maximumPoolSize`, HikariCP will make a best
effort to add additional connections quickly and efficiently. However, for maximum performance and responsiveness to
spike demands, it is recommended not setting this value and instead allowing HikariCP to act as a fixed size
connection pool.

|`password`
|
| Database user password

|`username`
|
|Database user name.
|===



.HikariCP DataSource Property Reference - Other Properties
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`allowPoolSuspension`
|`false`
|Controls whether the pool can be suspended and resumed through JMX

|`catalog`
| driver default
| The default catalog for databases that support the concept of catalogs. If this property is not specified,
the default catalog defined by the JDBC driver is used.

|`connectionInitSql`
|
| A SQL statement that will be executed after every new connection creation before adding it to the pool. If this SQL
is not valid or throws an exception, it will be treated as a connection failure and the standard retry logic will be
followed.

|`dataSourceClassName`
|
| The name of the DataSource class provided by the JDBC driver. Consult the documentation for your specific JDBC driver
to get this class name. XA data sources are not supported. XA requires a real transaction manager. You do not
need this property if you are using `jdbcUrl` for "old-school" DriverManager-based JDBC driver configuration.

|`dataSourceJNDI`
|
| JNDI name to use for DataSource lookup. JNDI is a rather foreign concept to Bootique, so this is rarely used if ever.

|`dataSourceProperties`
|
| A map of properties passed the DataSource created for `dataSourceClassName` property. Ignored if `dataSourceClassName`
is not in use and `jdbcUrl` is used.

|`driverClassName`
|
| Used to load a specific driver class via DriverManager. Usually cab be omitted, as the driver can be resolved from `jdbcUrl`.

|`initializationFailTimeout`
| 1
| Controls whether the pool will "fail fast" if the pool cannot be seeded with an initial connection successfully.
Any positive number is taken to be the number of milliseconds to attempt to acquire an initial connection; the
application thread will be blocked during this period. If a connection cannot be acquired before this timeout occurs,
an exception will be thrown. This timeout is applied after the `connectionTimeout` period. If the value is zero,
HikariCP will attempt to obtain and validate a connection. If a connection is obtained, but fails validation, an
exception will be thrown and the pool not started. However, if a connection cannot be obtained, the pool will start,
but later efforts to obtain a connection may fail. A value less than zero will bypass any initial connection attempt,
and the pool will start immediately while trying to obtain connections in the background. Consequently, later efforts
to obtain a connection may fail.

|`isolateInternalQueries`
| false
| Determines whether HikariCP isolates internal pool queries, such as the connection alive test, in their own
transaction. Since these are typically read-only queries, it is rarely necessary to encapsulate them in their own
transaction. This property only applies if `autoCommit` is disabled.

|`leakDetectionThreshold`
| 0
| Long value representing milliseconds. Controls the amount of time that a connection can be out of the pool before
a message is logged indicating a possible connection leak. A value of 0 means leak detection is disabled. Lowest
acceptable value for enabling leak detection is 2000 (2 seconds).

|`maxLifetime`
|1800000 (30 minutes)
|Long value representing milliseconds. Controls the maximum lifetime of a connection in the pool. An in-use connection
will never be retired, only when it is closed will it then be removed. On a connection-by-connection basis, minor
negative attenuation is applied to avoid mass-extinction in the pool. We strongly recommend setting this value, and it
should be several seconds shorter than any database or infrastructure imposed connection time limit. A value of
0 indicates no maximum lifetime (infinite lifetime), subject of course to the idleTimeout setting. The minimum allowed
value is 30000ms (30 seconds).

|`readOnly`
| false
| Boolean. Controls whether Connections obtained from the pool are in read-only mode by default. Some databases do
not support the concept of read-only mode, while others provide query optimizations when the Connection is set to
read-only. Whether you need this property or not will depend largely on your application and database.

|`registerMbeans`
| false
| Boolean. Controls whether or not JMX Management Beans ("MBeans") are registered or not.

|`schema`
|driver default
| Default schema for databases that support the concept of schemas. If not specified, the default schema defined by the
JDBC driver is used.

|`transactionIsolation`
| driver default
| Controls the default transaction isolation level of connections returned from the pool. If not specified, the default
transaction isolation level defined by the JDBC driver is used. Only use this property if you have specific isolation
requirements that are common for all queries. The value of this property is the constant name from the Connection class
such as TRANSACTION_READ_COMMITTED, TRANSACTION_REPEATABLE_READ, etc.

|`validationTimeout`
|5000
|Long value representing milliseconds. Controls the maximum amount of time that a connection will be tested for
aliveness. This value must be less than the `connectionTimeout`. Lowest acceptable validation timeout is 250 ms.
|===

"hikari-instrumented" inherits from "hikari" and supports an additional set of properties:

.HikariCP Instrumented Property Reference
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`health.connection99Percent`
|
|Represented by DurationRangeFactory object <<DurationRangeFactory,documented below>>.

|`health.connectivity`
|
| Configures "aliveness" health check. Represented by DurationRangeFactory object <<DurationRangeFactory,documented below>>.
|===


[#DurationRangeFactory]
.DurationRangeFactory Property Reference
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`critical`
| 5s
| Critical threshold duration. E.g. 5ms, 2s, 1hr

|`max`
|
| Max threshold duration. E.g. 5ms, 2s, 1hr

|`min`
|
| Min threshold duration. E.g. 5ms, 2s, 1hr

|`warning`
|
| Warning threshold duration. E.g. 5ms, 2s, 1hr
|===